[project]
name = "rhtml2text"
repository = "https://github.com/scottming/rhtml2text"

[build-system]
uild-backend = "maturin"
requires = ["maturin>=0.8.1,<0.9"]

[tool.maturin]
manylinux="off"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
